baseURL: ""
theme: hugobricks
defaultContentLanguage: en
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
  tr:
    languageName: Turkçe
    contentDir: content/tr
    weight: 2
    disabled: false